# Generated by Django 3.1.7 on 2022-02-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gray',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='SOME STRING', upload_to='gallery/'),
        ),
    ]
