# Generated by Django 3.1.7 on 2022-02-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220220_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='gray',
            new_name='filterPhoto',
        ),
    ]
