# Generated by Django 3.1.7 on 2022-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220222_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='', upload_to='gallery/'),
        ),
    ]
